services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: diploma_thesis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: batman05
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - diplom-network

  app:
    build: .
    container_name: diplom-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/diploma_thesis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: batman05
    networks:
      - diplom-network

volumes:
  pgdata:

networks:
  diplom-network:
